// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-Bk9ILAuPIGg0-IpKF5y6niqhz0Gawaw',
    appId: '1:424667508765:web:0f4b37a55b1a3ba0e896f4',
    messagingSenderId: '424667508765',
    projectId: 'lapor-book-66f08',
    authDomain: 'lapor-book-66f08.firebaseapp.com',
    storageBucket: 'lapor-book-66f08.appspot.com',
    measurementId: 'G-E7R9NQWB4E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs8cwWIALmZWnUUUWuTR63qbFaveEw6X8',
    appId: '1:424667508765:android:4a176757cb97a34be896f4',
    messagingSenderId: '424667508765',
    projectId: 'lapor-book-66f08',
    storageBucket: 'lapor-book-66f08.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBh6StTgowzvgFf5IuO8M6sjOnN1Lpy5JE',
    appId: '1:424667508765:ios:beb37909500e7b2fe896f4',
    messagingSenderId: '424667508765',
    projectId: 'lapor-book-66f08',
    storageBucket: 'lapor-book-66f08.appspot.com',
    iosBundleId: 'com.example.laporBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBh6StTgowzvgFf5IuO8M6sjOnN1Lpy5JE',
    appId: '1:424667508765:ios:f8224024a58e7b8de896f4',
    messagingSenderId: '424667508765',
    projectId: 'lapor-book-66f08',
    storageBucket: 'lapor-book-66f08.appspot.com',
    iosBundleId: 'com.example.laporBook.RunnerTests',
  );
}
