// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrVJp_6TlYBC7WC-gNpoD7_UxoO8F2WP4',
    appId: '1:591933818455:web:017e1264f76d3d87ec8512',
    messagingSenderId: '591933818455',
    projectId: 'lapor-book-2c8a7',
    authDomain: 'lapor-book-2c8a7.firebaseapp.com',
    storageBucket: 'lapor-book-2c8a7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgf-sodsm3VPgjUIWfBsXY_MAzJ46w9b8',
    appId: '1:591933818455:android:9420a534719ecf31ec8512',
    messagingSenderId: '591933818455',
    projectId: 'lapor-book-2c8a7',
    storageBucket: 'lapor-book-2c8a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBXry5mV2i5-KyyT5LxFkBhUYjrDwNvH0',
    appId: '1:591933818455:ios:7e994aba0078e5f2ec8512',
    messagingSenderId: '591933818455',
    projectId: 'lapor-book-2c8a7',
    storageBucket: 'lapor-book-2c8a7.appspot.com',
    iosBundleId: 'com.example.laporBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBXry5mV2i5-KyyT5LxFkBhUYjrDwNvH0',
    appId: '1:591933818455:ios:7e994aba0078e5f2ec8512',
    messagingSenderId: '591933818455',
    projectId: 'lapor-book-2c8a7',
    storageBucket: 'lapor-book-2c8a7.appspot.com',
    iosBundleId: 'com.example.laporBook',
  );
}
